# base image
FROM rabbitmq:management
# running required command
RUN rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_management_agent rabbitmq_shovel rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp rabbitmq_web_mqtt